# Generated by Django 2.2.3 on 2019-07-06 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthKit', '0002_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HealthKit.UserDetails')),
                ('specialization', models.CharField(max_length=50, verbose_name='Specialization')),
                ('degree', models.TextField()),
            ],
        ),
    ]
