# Generated by Django 2.2.3 on 2019-07-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthKit', '0004_doctorresponse_patientrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorresponse',
            name='request',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='HealthKit.PatientRequest'),
            preserve_default=False,
        ),
    ]
